version: "3.7"
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    hostname: postgres-server
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=keycloak"
      - "POSTGRES_USER=keycloak"
      - "POSTGRES_DB=keycloak"